### ISSUE TITLE
Host playground

### ISSUE THREAD

**Issue by jonatanklosko** [the-mikedavis/tree-sitter-iex#7]
We can host playground on GH pages and have CI updating the parser file. When we get to a nice setup we can do the same on tree-sitter-elixir.

**Comment by the-mikedavis** [comment]
I tinkered with `tree-sitter-git-commit` and found a way that seems to work well:

1. create an orphan branch `git checkout --orphan gh-pages`
    - looks like `gh-pages` is common for historical reasons but we could use any branch name afaik
2. unstage and remove everything
3. move the old `docs/*` content into the repository root
4. fix the [wasm url](https://github.com/the-mikedavis/tree-sitter-git-commit/blob/63d885b0a7b8b526b19559f4a49f23fb4438b3cf/playground.js#L85) in `playground.js`
5. commit and push the new `gh-pages` branch
6. checkout main
7. setup wasm generation and auto-commit in `.github/workflows/generate-parser.yml` (see [here](https://github.com/the-mikedavis/tree-sitter-git-commit/compare/20a2a534eedb22feb4eb6e7c8f0ef6fe8f186dc5..cc2beee7721ab9be499a63933633f88749901055))
8. commit and push that change and then actions will take care of the rest!

What do you think, :shipit:? I can make the new branch and a PR for the workflow change but I think we'll need someone with the right priviledges in the organization to setup the pages settings. Here's what they look like for tree-sitter-git-commit:

<img src="https://user-images.githubusercontent.com/21230295/148691977-a04487fe-37f5-4a3b-b9ff-2565a747ddd8.png" width=500 />

**Comment by jonatanklosko** [comment]
@the-mikedavis all sounds great, please go ahead!

**Comment by jonatanklosko** [comment]
And actually I'm thinking it may be an overkill for IEx, so maybe do it for tree-sitter-elixir for now?

**Comment by the-mikedavis** [comment]
I think you're right, it might just be confusing since it won't be able to do injections
